-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

-- //sellnpc powder
profiles['powder'] = S{
    'prize powder',
    }

-- //sellnpc ore
profiles['ore'] = S{
    'iron ore',
    'copper ore',
    'tin ore',
    }

-- //sellnpc junk
profiles['junk'] = S{
    'chestnut',
    'san d\'Or. carrot',
	'Acheron Shield',
    'prize powder',
	'Honey',
	'beehive chip',
	'Colibri Beak',
	'Colibri Feather',
	'Shivite',
	'Ifritite',
	'Leviatite',
	'Garudite',
	'Ramuite',
	'Titanite',
	'Flame Geode',
	'Soil Geode',
	'Breeze Geode',
	'Aqua Geode',
	'Light Geode',
	'Snow Geode',
	'Shadow Geode',
	'Carbite',
	'Fenrite',
	'Pugil Scales',
	'Shall Shell',
	'Bird Egg',
	'Flytrap Leaf',
	'Land Crab Meat',
	'Revival Tree Root',
	'Bone Chip',
	'Puk Egg',
	'Bird Feather',
	'Apkallu Egg',
	'Apkallu Feather',
	'Vanilla',
	'Bat Fang',
	'Crawler Cocoon',
	'Tree Cuttings',
	'Sage',
	'Vegetable Seeds',
	'Sage',
	'Black Prawn',
	'Cone Calamary',
	'Elshimo Newt',
	'Deathball',
	'Giant Catfish',
	'Cobalt Jellyfish',
	'Moat Carp',
	'Zebra Eel',
	'Woozyshroom',
	'King Truffle',
	'Black Eel',
	'Crayfish',
	'Gugru Tuna',
	'Moorish Idol',
	'Yayinbaligi',
	'Contortopus',
	'Bay Leaves',
	'Black Pepper',
	'Flax Flower',
	'Sheep Tooth',
	'Holy Basil',
	'Igneous Rock',
	'Pine Nuts',
	'Auric Sand',
	'Adoulinian Kelp',
	'Bluetail',
	'Bastore Bream',
	'Crescent Fish',
	'Ca Cuong',
	'Barnacle',
	'Senroh Sardine',
	'Kazham Peppers',
	'Mhaura Garlic',
	'Divine Log',
	'Beetle Jaw',
	'Fish Bones',
	'Chunk of Aht Uhrgan Brass',
	'Faerie Apple',
	'Pipira',
	'Clump of Windurstian Tea Leaves',
	'Elm Log',
	'Walnut Log',
	'Grimmonite',
	'Red Terrapin',
	'Gigant Squid',
	'Gavial Fish',
	'Three-eyed Fish',
	'Copper Frog',
	'Black Ghost',
	'Maple Log',
	'Ash Log',
	'Ebony Log',
	'Dogwood Log',
	'Adaman Ore',
	'Elshimo Pachira Fruit',
	'Snapping Mole',
	'Dark Bass',
	'Mackerel',
	'Ball of Saruta Cotton',
	'Bag of Grove cuttings',
	'Felicifruit',
	'Black Sole',
	'Watermelon',
	'Sprig of Misareaux Parsley',
	'Ulbukan Lobster',
	'Cactus Stems',
	'Tree Saplings',
	'King Locust',
	'Skull Locust',
	'Urunday Log',
	'Dragon Talon',
	'Acorn',
	'Dragon Bone',
	'Sprig of Fresh Marjoram',
	'Chunk of Orichalcum Ore',
	'Mahogany Log',
	'Arrowwood Log',
	'Chunk of Khroma Ore',
	'Chunk of Iron Ore',
	'Meteorite',
	'Brass Loach',
	'Bhefhel Marlin',
	'Eggplant',
	'Ajari Necklace',
	'Philomath Stole',
	'Dem Ring',
	'Altep Ring',
	'Pearl',
	'Black Pearl',
	'Zircon',
	'Sunstone',
	'Jadeite',
	'Painite',
	'Chrysoberyl',
	'Fluorite',
	'Moonstone',
	'Gold Ingot',
	'Mythril Ingot',
	'Darksteel Ingot',
	'Blue Rock',
	'Oxblood',
	
	
    }
-- //sellnpc armor
profiles['mog'] = S{
	'Lacquer Tree Log',
	'Arrowwood Log',
	'Maple Log',
	'Ash Log',
	'Chestnut',
	'Acorn',
	'Faerie Apple',
	'Stone',
	'Stone II',
	'Ether',

	}
return profiles
