xivhotbar_keybinds_job['Base'] = {
 -- Hotbar #1
 {'b 1 8',  'ja', 'Weapon Bash', 't', 'Bash',"Dark_Spear"},
  {'b 1 9',  'ma', 'Stun', 'stnpc', 'Stun',"tile959"},
    {'b 1 10',  'ma', 'Absorb-Attri', 'stnpc', 'Absorb',"Unholy_Feast"},
    {'b 1 7', 'ja', 'Nether Void', 'me', 'Drn++',"Sand_Flare"},
	{'b 1 5', 'ja', 'Dark Seal', 'me', 'D.Mac','GatheringPlague'},
	{'b 1 6', 'ja', 'Arcane Circle', 'me', 'A.Crcl',"Putrid_Mark"},  
 -- Hotbar #2

 {'b 2 3', 'ma', 'Drain II', 't', 'Drain II',"Gormandize"},
 {'b 2 4', 'ma', 'Drain III', 't', 'Drain 3',"Feast_of_Corruption"},
 {'b 2 5', 'ma', 'Aspir II', 't', 'Aspir II',"Life_Transfer"},
	{'b 2 6', 'ja', 'Arcane Crest', 't', 'Crest',"Spectral_Armor"},  
  {'b 2 7', 'ja', 'Last Resort', 'me', 'L.Rsrt', "LastResort"},
  {'b 2 8', 'ja', 'Souleater', 'me', 'S.Etr',"Harbinger_Shroud"},
   {'b 2 9', 'ma', 'Poisonga', 't', 'Psnga', "Spider_Venom"},
     {'b 2 10', 'ma', 'Poison', 't', 'Psn',"tile056"},
  --{'b 2 9', 'ja', 'Consume Mana', 'me', 'M.Burst'},
 -- Hotbar #3
 {'b 3 1', 'ma', 'Bio II', 'stnpc', 'Bio',"tile036"},
 {'b 3 2', 'ma', 'Poison', 'stnpc', 'Psn',"tile056"},
  --{'b 3 2', 'ma', 'Absorb-ACC', 't', 'ACC'},
   {'b 3 3', 'ma', 'Absorb-STR', 't', 'STR',"Well_of_Power"},
    {'b 3 4', 'ma', 'Absorb-TP', 't', 'TP',"Locust_Swarm"},
	 --{'b 3 5', 'ma', 'Absorb-DEX', 't', 'DEX'},
	  {'b 3 5', 'ma', 'Absorb-VIT', 't', 'VIT',"Enfeebling_Blood"},

 -- Hotbar #4
    {'b 4 4', 'ma', 'Tractor', 'stpc', 'Tractr',"Signet_of_Undeath"},
  {'b 4 7', 'ma', 'Dread Spikes', 'me', 'Spikes', "Death_Shroud"},
   {'b 4 8', 'ma', 'Endark II', 'me', 'Endrk',"Life_Rend"},
    {'b 4 9',  'ja', 'Scarlet Delirium', 'me', 'Dlrium',"Shadowed_Vigil_Icon"},
 --
 {'f 1 7', 'ma', 'Sleep II', 'stnpc', 'Sleep','tile944'},
 {'f 1 8', 'ma', 'Bind', 'stnpc', 'Bind',"tile959"},
 {'f 1 9', 'ma', 'Break', 'stnpc', 'Break'},
  {'f 2 3', 'ma', 'Poisonga', 't', 'Psnga', "Spider_Venom"},
   {'f 4 10', 'ja', 'Blood Weapon', 'me', 'Blood'},
    {'f 4 9', 'ja', 'Soul Enslavement', 'me', 'TP Drain'},
	
	{'f 4 1', 'ma', 'Fire III', 't', 'Fire',"tile054"},
	{'f 4 2', 'ma', 'Blizzard III', 't', 'Bliz.',"tile053"},
	{'f 4 3', 'ma', 'Thunder III', 't', 'Thun.',"tile055"},
	{'f 4 4', 'ma', 'Aero III', 't', 'Aero',"tile056"},
	{'f 4 5', 'ma', 'Stone III', 't', 'Stone',"tile031"},
	{'f 4 6', 'ma', 'Water III', 't', 'Water',"tile085"},
}

xivhotbar_keybinds_job['Great Sword'] = {
	-- Battle
    {'b 1 1', 'weaponskill', 'Torcleaver', 'stnpc', 'Torclvr', 'Torcleaver2'},
	{'b 1 3', 'weaponskill', 'Spinning Slash', 't', 'S.Slash', 'GS-Single2'},
	{'b 1 2', 'weaponskill', 'Resolution', 't', 'Reso', 'GS-Single3'},
	{'b 1 4', 'weaponskill', 'Shockwave', 't', 'Shock.', 'GS-AoE'}, 
	--
    {'f 1 1', 'weaponskill', 'Torcleaver', 'stnpc', 'Torclvr', 'Torcleaver2'},
	{'f 1 3', 'weaponskill', 'Spinning Slash', 't', 'S.Slash', 'GS-Single2'},
	{'f 1 2', 'weaponskill', 'Resolution', 't', 'Reso.', 'GS-Single3'},
	{'f 1 4', 'weaponskill', 'Shockwave', 't', 'Shock.', 'GS-AoE'},
}
xivhotbar_keybinds_job['Scythe'] = {
	-- Battle
    {'b 1 3', 'weaponskill', 'Quietus', 't', 'Qietus', 'Guillotine'},
    {'b 1 2', 'weaponskill', 'Insurgency', 't', 'Insurg.', 'Reaper'},
	{'b 1 4', 'weaponskill', 'Entropy', 't', 'Entrp.', 'Nightmare'},
	{'b 1 1', 'weaponskill', 'Cross Reaper', 'stnpc', 'Reap.', 'Reaper2'},
	{'b 2 1', 'weaponskill', 'Catastrophe', 'stnpc', 'Cata', 'Cata'},
	{'b 2 2', 'weaponskill', 'Spiral Hell', 't', 'S.Hell', 'Hell'},

    {'f 1 3', 'weaponskill', 'Quietus', 't', 'Qietus', 'Guillotine'},

	{'f 1 4', 'weaponskill', 'Entropy', 't', 'Entrp.', 'Nightmare'},
	{'f 1 5', 'weaponskill', 'Spinning Scythe', 't', 'AoE'},
	{'f 1 1', 'weaponskill', 'Cross Reaper', 'stnpc', 'Reap.', 'Reaper2'},
	{'f 1 2', 'weaponskill', 'Catastrophe', 't', 'Cata', 'Cata'},
	{'f 2 1', 'weaponskill', 'Infernal Scythe', 't', 'Infrnl'},
}
xivhotbar_keybinds_job['Great Axe'] = {
	-- Battle
    {'b 1 1', 'weaponskill', 'Upheaval', 'stnpc', 'Uphvl', 'Core_Cleave'},
	{'b 1 2', 'weaponskill', 'Steel Cyclone', 't', 'S.Clne', 'Malicious_Cunning_Salvo'},
	{'b 1 3', 'weaponskill', 'Fell Cleave', 't', 'AoE', 'Symbol_of_Vengeance'},
	{'b 1 4', 'weaponskill', 'Armor Break', 't', 'Armor', 'Kayle_Radiant_Blast_2_HD'},	

    {'f 1 1', 'weaponskill', 'Upheaval', 'stnpc', 'Uphvl', 'Core_Cleave'},
	{'f 1 2', 'weaponskill', 'Steel Cyclone', 't', 'S.Clne', 'Malicious_Cunning_Salvo'},
	{'f 1 3', 'weaponskill', 'Fell Cleave', 't', 'AoE', 'Symbol_of_Vengeance'},
	{'f 1 4', 'weaponskill', 'Armor Break', 't', 'Armor', 'Kayle_Radiant_Blast_2_HD'},
}
xivhotbar_keybinds_job['Sword'] = {
	-- Battle
	{'b 1 1', 'weaponskill',  'Savage Blade', 'stnpc', 'Savge', 'Sword-Single3'},
	{'b 1 2', 'weaponskill',  'Requiescat', 't', 'Rqsct', 'Sword-Requiescat'},	
}
xivhotbar_keybinds_job['Axe'] = {
	-- Battle
	{'b 1 2', 'weaponskill', 'Ruinator', 't', 'Ruin ', 'Ruinator'},
	{'b 1 1', 'weaponskill', 'Decimation', 't', 'Decmt', 'Decimation'},
	{'b 1 3', 'weaponskill', 'Smash Axe', 't', 'Stun', 'Axe-Single'},
}
xivhotbar_keybinds_job['Club'] = {
	-- Battle 
	{'b 1 1', 'weaponskill',  'Judgment', 't', 'Judge','Club-Single'},  
	{'b 1 2', 'weaponskill',  'Flash Nova', 't', 'Nova', 'Nova'}, 
}

xivhotbar_keybinds_job['WAR'] = {
    {'b 4 4',  'ja', 'Provoke', 'stnpc', 'Prov.',"tile150"},
    {'b 3 7',  'ja', 'Berserk', 'me', 'Brsrk', 'Berserk'},
    {'b 3 9',  'ja', 'Warcry', 'me', 'War.', 'Warcry'},
	{'b 3 8', 'ja', 'Aggressor', 'me', 'Aggr.', 'Agressor'},
}

xivhotbar_keybinds_job['SAM'] = {
    {'b 4 10',  'ja', 'Hasso', 'me', 'Hasso', 'Dragon_Trigger'},
    {'b 3 7',  'ja', 'Meditate', 'me', 'Med.', 'Meditate'},
    {'b 3 8',  'ja', 'Sekkanoki', 'me', 'Sek.', 'Sekkanoki'},
	{'b 2 6',  'ja', 'Third Eye', 'me', 'Third.', 'Third'},
	{'b 1 6',  'ja', 'Seigan', 'me', 'Seign', 'Seigan'},
	{'b 4 1', 'ja', 'Arcane Circle', 'me', 'A.Circ',"Putrid_Mark"},  
	{'b 4 2', 'ja', 'Arcane Crest', 't', 'Crest',"Spectral_Armor"},
	{'b 4 3', 'ja', 'Warding Circle', 'me', 'D.Circ',"Winds_of_Disenchantment"},
}
xivhotbar_keybinds_job['THF'] = {
	-- Battle
	{'f 2 7', 'ja', 'Sneak Attack', 'me', 'Snk.Atk', 'snkatk'},
	{'f 2 8', 'ja', 'Trick Attack', 'me', 'Trk.Atk', 'Innin'},
	{'f 2 10', 'ja', 'Flee', 'me', 'Flee', 'Flee'},
	{'f 2 9', 'ja', 'Hide', 'me', 'Hide', 'Hide'},
}
xivhotbar_keybinds_job['RDM'] = {
	--{'b 1 9', 'ma', 'Phalanx', 'me', 'Phalanx', 'Stoneskin'},

	{'f 4 1', 'ma', 'Stone II', 't', 'Stn'},
	{'f 4 2', 'ma', 'Water II', 't', 'Wtr'},
	{'f 4 3', 'ma', 'Aero II', 't', 'Aero'},
	{'f 1 10', 'ja', 'Convert', 'me', 'Convert'},
	{'f 3 3', 'ma', 'Refresh', 'stpc', 'Rfrsh'},
	{'f 2 4', 'ma', 'Haste', 'stpc', 'Haste'},
	{'f 2 1', 'ma', 'Diaga', 't', 'Diaga'},
	{'f 2 2', 'ma', 'Dia', 't', 'Dia'},
	{'f 2 7', 'ma', 'Stoneskin', 'me', 'StnSkn',"tile639"},
	{'f 2 8', 'ma', 'Enfire', 'me', 'En-Ele'},
	{'f 1 9', 'ma', 'Phalanx', 'me', 'Phalnx'},

	{'f 3 1', 'ma', 'Protect III', 'me', 'Prtct'},
	{'f 3 2', 'ma', 'Shell II', 'me', 'Shell'},	
	{'f 4 9', 'ma', 'Sneak', 'me', 'Snk'},
	{'f 4 10', 'ma', 'Invisible', 'me', 'Invs'},
}
xivhotbar_keybinds_job['NIN'] = {
	-- Battle
	{'b 4 1', 'ma', 'Utsusemi: Ichi', 'me', "Utsu", 'UtsuIchi'},
	{'b 4 2', 'ma', 'Utsusemi: Ni', 'me', "Utsu", 'UtsuNi'},
	{'f 4 9', 'ma', 'Monomi: Ichi', 'me', 'Snk'},
	{'f 4 10', 'ma', 'Tonko: Ichi', 'me', 'Invs'},
}
xivhotbar_keybinds_job['DNC'] = {
	-- Battle
	{'b 4 1', 'ja', 'Box Step', 't', 'Box', 'Box'},
		{'b 4 10', 'ja', 'Reverse Flourish', 'me', 'Rvrs', 'Reverse'},
		{'b 4 3', 'ja', 'Divine Waltz', 'stpc', 'Cura', 'Divine'},
		{'b 4 2', 'ja', 'Curing Waltz III', 'stpc', 'CureIII', 'CureIII'},
		{'b 4 5', 'ja', 'Healing Waltz', 'stpc', 'Erase', 'Esuna'},
		{'b 3 7', 'ja', 'Spectral Jig', 'me', 'Spctrl', 'Spectral'},
		{'b 3 8', 'ja', 'Chocobo Jig', 'me', 'Chcbo', 'Chocobo'},
}
xivhotbar_keybinds_job['RUN'] = {
    {'f 4 2',  'ja', 'Lunge', 't', 'Lnge', 'Lunge'},
    {'f 4 1',  'ja', 'swipe', 't', 'Swipe', 'Swipe'},
	
	{'f 3 1', 'ja', 'Ignis', 'me', 'Ice', 'Activate..._(red)'},
    {'f 3 2', 'ja', 'Gelus', 'me', 'Wind', 'Ice_Wall'},
    {'f 3 3', 'ja', 'Flabra', 'me', 'Earth', 'Activate..._(green)'},
    {'f 3 4', 'ja', 'Tellus', 'me', 'Thun.', 'Activate..._(yellow)'},
    {'f 3 5', 'ja', 'Sulpor', 'me', 'Water', 'Activate..._(purple)'},
    {'f 3 6', 'ja', 'Unda', 'me', 'Fire', 'Activate..._(blue)'},
    {'f 3 7', 'ja', 'Lux', 'me', 'Dark', 'Center_Your_Mind'},
    {'f 3 8', 'ja', 'Tenebrae', 'me', 'Light', 'Call_Forth_Magic'},
	
	{'f 2 6', 'ma', 'Barfire', 'me', 'Fire'},
	{'f 2 1', 'ma', 'Barblizzard', 'me', 'Ice'},
	{'f 2 4', 'ma', 'Barthunder', 'me', 'Thun'},
	{'f 2 2', 'ma', 'Baraero', 'me', 'Wind'},
	{'f 2 5', 'ma', 'Barwater', 'me', 'Water'},
	{'f 2 3', 'ma', 'Barstone', 'me', 'Earth'},
	
	{'f 4 3', 'ja', 'Vallation', 'me', 'Val.', 'Vallation'},
	{'f 4 4', 'ja', 'Valiance', 'me', 'Val+', 'Valiance'},
	{'f 4 6', 'ja', 'Pflug', 'me', 'Pflug', 'Valiance'},
	{'f 4 5', 'ja', 'Swordplay', 'me', 'Sword.', 'Swordplay'},
	{'f 1 6', 'ma', 'Flash', 'stnpc', 'Flash'},	

	
	{'f 2 7', 'ma', 'Barsleep', 'me', 'B.Slp'},
	{'f 2 8', 'ma', 'Barparalyze', 'me', 'B.Para'},
	{'f 2 9', 'ma', 'Barsilence', 'me', 'B.Sil'},
}
xivhotbar_keybinds_job['DRG'] = {
	{'b 4 1',  'ja', 'Jump', 't', 'Jump', 'Jump'},
	{'b 4 2',  'ja', 'High Jump', 't', 'H. Jump', 'High Jump'},
	{'b 4 3',  'ja', 'Super Jump', 't', 'Enmity-', 'Super Jump'},
	{'b 4 5',  'ja', 'Ancient Circle', 'me', 'DRG.Circ',"Rise_of_the_Dragon"},
}
xivhotbar_keybinds_job['BLM'] = {
	{'f 4 10', 'ja', 'Elemental Seal', 'me', 'E.Seal'},
	{'f 4 1', 'ma', 'Warp', 'me', 'Warp'},
 	{'f 4 2', 'ma', 'Warp II', 'stpc', 'WarpII'},
 	{'f 4 4', 'ma', 'Sleepga', 't', 'Slpga'},
	{'f 2 9', 'ma', 'Ice Spikes', 'me', 'Ice'},
}
xivhotbar_keybinds_job['WHM'] = {
	{'f 4 1', 'ma', 'Teleport-Dem', 'me', 'Dem'},	
	{'f 4 2', 'ma', 'Teleport-Mea', 'me', 'Mea'},	
	{'f 4 3', 'ma', 'Teleport-Holla', 'me', 'Holla'},	
	{'f 4 4', 'ma', 'Haste', 'me', 'Haste'},
}
return xivhotbar_keybinds_job